---
extends: 'eslint:recommended'
rules:
    eqeqeq: 2
    no-unexpected-multiline: 2
    # valid-jsdoc: 2
    dot-notation: 2
    no-caller: 2
    no-eval: 2
    no-extend-native: 2
    no-extra-bind: 2
    babel/no-invalid-this: 2
    no-iterator: 2
    no-magic-numbers:
        - 2
        - ignore: [-1, 0, 1, 2]
    no-multi-spaces: 2
    no-native-reassign: 2
    no-new: 2
    no-proto: 2
    no-redeclare: 2
    no-useless-call: 2
    no-useless-escape: 0
    vars-on-top: 2
    wrap-iife: [2, inside]
    no-unused-vars:
        - 2
        - vars: local
          args: after-used
    no-new-require: 2
    no-path-concat: 2
    no-sync: 2
    array-bracket-spacing: [2, never]
    block-spacing: [2, always]
    brace-style:
        - 2
        - 1tbs
        - allowSingleLine: true
    comma-dangle: ['error', 'only-multiline']
    comma-spacing:
        - 2
        - before: false
          after: true
    comma-style: [2, last]
    consistent-this: [2, self]
    eol-last: [2, unix]
    key-spacing:
        - 2
        - beforeColon: false
          afterColon: true
    max-depth: 2
    new-cap:
        - 2
        - capIsNewExceptions: ['$.Deferred']
    new-parens: 2
    newline-after-var: 2
    no-array-constructor: 2
    no-bitwise: 2
    no-continue: 2
    no-lonely-if: 2
    no-nested-ternary: 2
    no-new-object: 2
    no-spaced-func: 2
    no-unneeded-ternary: 2
    object-curly-spacing: [2, always]
    semi-spacing: 2
    semi: [2, always]
    keyword-spacing: 2
    # space-after-keywords: [2, always]
    # space-before-keywords: [2, always]
    # space-return-throw-case: 2
    space-before-blocks: [2, always]
    space-before-function-paren: [2, never]
    space-in-parens: [2, never]
    space-infix-ops: 2
env:
    browser: true
    node: true
    es6: true
    mocha: true
parser: 'babel-eslint'
parserOptions:
    ecmaVersion: 2017
    allowImportExportEverywhere: true
    ecmaFeatures:
        classes: true
        modules: true
        jsx: true
        experimentalObjectRestSpread: true
    sourceType: 'module'
globals:
    afterAll: true
    afterEach: true
    expect: true
    Back: true
    beforeAll: true
    beforeEach: true
    CSSPlugin: true
    define: true
    describe: true
    Draggable: true
    findByDataAutomation: true
    getToystoreOriginalComponentRef: true
    it: true
    jest: true
    mocha: true
    mockComponent: true
    mockServer: true
    mount: true
    Power1: true
    Power2: true
    Power3: true
    React: true
    sandbox: true
    shallow: true
    sinon: true
    SlowMo: true
    TimelineLite: true
    TweenLite: true
    TweenMax: true
plugins:
    - 'babel'
